"""empty message

Revision ID: f75181efca3f
Revises: 37b9319c746f
Create Date: 2023-10-09 12:41:43.147856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75181efca3f'
down_revision = '37b9319c746f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_restaurant_pizzas_restaurnt_id_restaurants', 'restaurant_pizzas', type_='foreignkey')
    op.create_foreign_key(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurant_pizzas', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('restaurant_pizzas', 'restaurnt_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_pizzas', sa.Column('restaurnt_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurant_pizzas', type_='foreignkey')
    op.create_foreign_key('fk_restaurant_pizzas_restaurnt_id_restaurants', 'restaurant_pizzas', 'restaurants', ['restaurnt_id'], ['id'])
    # ### end Alembic commands ###
